# Generated by Django 2.0.6 on 2019-01-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20190115_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
