# Generated by Django 2.0.6 on 2019-01-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of things', 'Internet of things'), ('Web App', 'Web App'), ('Android', 'Android'), ('Games', 'Games'), ('others..', 'others..')], max_length=30),
        ),
    ]
