# Generated by Django 2.0.6 on 2019-01-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_auto_20190115_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Internet of things', 'Internet of things'), ('Web App', 'Web App'), ('Android', 'Android'), ('Games', 'Games'), ('others..', 'others..')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
