# Generated by Django 2.0.6 on 2019-01-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_auto_20190115_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='report',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='earn',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
