# Generated by Django 2.0.6 on 2019-01-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_auto_20190117_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.CharField(max_length=30),
        ),
    ]
