# Generated by Django 2.0.6 on 2019-01-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0013_auto_20190118_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
